---
abstract: 'Patching TAP::DOM, usually for test waivers'
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-DOM-Waivers
requires:
  Clone: 0
  Data::DPath: 0.42
  Data::Dumper: 0
  File::Temp: 0
  Sub::Exporter: 0
  TAP::Base: 0
  TAP::DOM: 0.06
  Test::Harness: 3.22
  Test::More: 0
  YAML::Any: 0
  accessors: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=TAP-DOM-Waivers
  homepage: http://metacpan.org/release/TAP-DOM-Waivers
  repository: git://github.com/renormalist/tap-dom-waivers.git
version: 0.001
x_Dist_Zilla:
  perl:
    version: 5.016003
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@SCHWIGON/@Basic/GatherDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@SCHWIGON/@Basic/PruneCruft'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@SCHWIGON/@Basic/ManifestSkip'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@SCHWIGON/@Basic/MetaYAML'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::License
      name: '@SCHWIGON/@Basic/License'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@SCHWIGON/@Basic/Readme'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@SCHWIGON/@Basic/ExtraTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@SCHWIGON/@Basic/ExecDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@SCHWIGON/@Basic/ShareDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@SCHWIGON/@Basic/MakeMaker'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@SCHWIGON/@Basic/Manifest'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@SCHWIGON/@Basic/TestRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@SCHWIGON/@Basic/ConfirmRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@SCHWIGON/@Basic/UploadToCPAN'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@SCHWIGON/MetaConfig'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@SCHWIGON/MetaJSON'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@SCHWIGON/PkgVersion'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@SCHWIGON/PodSyntaxTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@SCHWIGON/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@SCHWIGON/PodCoverageTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@SCHWIGON/MetaResources'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@SCHWIGON/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@SCHWIGON/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@SCHWIGON/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@SCHWIGON/AutoPrereqs'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@SCHWIGON/Git::Describe'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@SCHWIGON/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@SCHWIGON/NextRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@SCHWIGON/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@SCHWIGON/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@SCHWIGON/@Git/Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@SCHWIGON/@Git/Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@SCHWIGON/@Git/Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@SCHWIGON/@Git/Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300034
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300034
x_authority: cpan:SCHWIGON
